name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag nasir.id:latest && sudo docker run --name nasir.id -p 80:80 -d nasir:latest
